const data = {
  products: [
    {
      name: "Nice Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/image1.jpg",
      price: 50,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      name: "Adidas Slim Shirt",
      slug: "Adidas-slim-shirt",
      category: "Shirts",
      image: "/images/image1.jpg",
      price: 60,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      name: "Balmain Slim Shirt",
      slug: "balmain-slim-shirt",
      category: "Shirts",
      image: "/images/image1.jpg",
      price: 50,
      countInStock: 10,
      brand: "Balmain",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      name: "Johnson Slim Shirt",
      slug: "johnson-slim-shirt",
      category: "Shirts",
      image: "/images/image1.jpg",
      price: 30,
      countInStock: 3,
      brand: "Johnson",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
  ],
};
export default data;
